# Generated by Django 5.0.14 on 2026-02-04 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attempts', '0001_initial'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('form_level', models.PositiveSmallIntegerField()),
                ('academic_year', models.PositiveIntegerField()),
                ('term', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_students', models.PositiveIntegerField(default=50)),
                ('join_code', models.CharField(blank=True, max_length=8, unique=True)),
                ('allow_join', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Classes',
                'ordering': ['-academic_year', 'form_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('school_type', models.CharField(choices=[('government', 'Government'), ('private', 'Private'), ('mission', 'Mission'), ('trust', 'Trust')], max_length=20)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='schools/logos/')),
                ('primary_color', models.CharField(default='#3B82F6', max_length=7)),
                ('parent_portal_enabled', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('total_teachers', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('hod', 'Head of Department'), ('deputy', 'Deputy Head'), ('head', 'Headmaster/Headmistress')], default='teacher', max_length=20)),
                ('can_create_assignments', models.BooleanField(default=True)),
                ('can_view_school_analytics', models.BooleanField(default=False)),
                ('can_manage_teachers', models.BooleanField(default=False)),
                ('can_manage_students', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_school_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('assignment_type', models.CharField(choices=[('paper', 'Full Paper'), ('topics', 'Topic Practice'), ('custom', 'Custom Questions'), ('quiz', 'Quick Quiz')], max_length=20)),
                ('total_marks', models.PositiveIntegerField(default=0)),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('attempts_allowed', models.PositiveSmallIntegerField(default=1)),
                ('show_answers_after', models.BooleanField(default=True)),
                ('available_from', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('late_submission_allowed', models.BooleanField(default=False)),
                ('late_penalty_percent', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('notify_on_publish', models.BooleanField(default=True)),
                ('remind_before_due', models.BooleanField(default=True)),
                ('notify_parents', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('papers', models.ManyToManyField(blank=True, to='exams.paper')),
                ('questions', models.ManyToManyField(blank=True, to='exams.question')),
                ('topics', models.ManyToManyField(blank=True, to='exams.topic')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('late', 'Submitted Late'), ('graded', 'Graded')], default='not_started', max_length=20)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('marks_earned', models.PositiveIntegerField(default=0)),
                ('marks_possible', models.PositiveIntegerField(default=0)),
                ('percentage_score', models.FloatField(blank=True, null=True)),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('teacher_feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='schools.assignment')),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attempts.attempt')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
