# Generated by Django 5.0.14 on 2026-02-04 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attempts', '0001_initial'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('questions_attempted', models.PositiveIntegerField(default=0)),
                ('questions_correct', models.PositiveIntegerField(default=0)),
                ('marks_earned', models.PositiveIntegerField(default=0)),
                ('marks_possible', models.PositiveIntegerField(default=0)),
                ('streak_maintained', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_attempted', models.PositiveIntegerField(default=0)),
                ('questions_correct', models.PositiveIntegerField(default=0)),
                ('total_marks_earned', models.PositiveIntegerField(default=0)),
                ('total_marks_possible', models.PositiveIntegerField(default=0)),
                ('mastery_level', models.CharField(choices=[('not_started', 'Not Started'), ('beginner', 'Beginner'), ('developing', 'Developing'), ('proficient', 'Proficient'), ('mastered', 'Mastered')], default='not_started', max_length=20)),
                ('mastery_score', models.FloatField(default=0)),
                ('last_practiced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_practiced_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMarkingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_sent', models.TextField()),
                ('model_used', models.CharField(max_length=50)),
                ('response_received', models.TextField()),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('marks_awarded', models.PositiveIntegerField(default=0)),
                ('confidence_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marking_logs', to='attempts.answer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('folder', models.CharField(choices=[('default', 'Saved Questions'), ('review', 'Review Later'), ('difficult', 'Difficult Questions'), ('favorite', 'Favorites')], default='default', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='exams.question')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
