# Generated by Django 5.0.14 on 2026-02-06 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_add_paper_types'),
        ('library', '0001_initial'),
        ('progress', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='bookmark_type',
            field=models.CharField(choices=[('question', 'Question'), ('paper', 'Paper'), ('resource', 'Resource')], default='question', max_length=20),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='exams.paper'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='library.resource'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='exams.question'),
        ),
    ]
