# Generated by Django 5.0.14 on 2026-02-04 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('country', models.CharField(default='Zimbabwe', max_length=100)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='boards/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('o_level', 'O Level'), ('a_level', 'A Level'), ('igcse', 'IGCSE'), ('as_level', 'AS Level')], max_length=20)),
                ('syllabus_code', models.CharField(blank=True, max_length=20)),
                ('year_from', models.IntegerField(blank=True, null=True)),
                ('year_to', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='exams.examinationboard')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='exams.subject')),
            ],
            options={
                'verbose_name_plural': 'Syllabi',
                'ordering': ['board', 'subject', 'level'],
                'unique_together': {('board', 'subject', 'level')},
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('paper_type', models.CharField(choices=[('paper_1', 'Paper 1'), ('paper_2', 'Paper 2'), ('paper_3', 'Paper 3'), ('practical', 'Practical'), ('theory', 'Theory')], max_length=20)),
                ('year', models.IntegerField()),
                ('session', models.CharField(choices=[('june', 'June'), ('november', 'November'), ('march', 'March')], max_length=20)),
                ('duration_minutes', models.IntegerField(default=120)),
                ('total_marks', models.IntegerField(default=100)),
                ('instructions', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='papers/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='exams.syllabus')),
            ],
            options={
                'ordering': ['-year', 'session', 'paper_type'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('objectives', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='exams.topic')),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='exams.syllabus')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('syllabus', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.CharField(max_length=20)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('short_answer', 'Short Answer'), ('long_answer', 'Long Answer'), ('structured', 'Structured'), ('essay', 'Essay')], max_length=20)),
                ('marks', models.IntegerField(default=1)),
                ('options', models.JSONField(blank=True, help_text='List of options for MCQ: [{"key": "A", "text": "Option A"}, ...]', null=True)),
                ('correct_answer', models.CharField(blank=True, help_text='For MCQ: the key of correct option (A, B, C, D)', max_length=10)),
                ('marking_scheme', models.TextField(blank=True, help_text='Marking guidelines for AI marking')),
                ('sample_answer', models.TextField(blank=True)),
                ('topic_text', models.CharField(blank=True, max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.paper')),
                ('topics', models.ManyToManyField(blank=True, related_name='questions', to='exams.topic')),
            ],
            options={
                'ordering': ['paper', 'order', 'question_number'],
            },
        ),
    ]
