# Generated by Django 5.0.14 on 2026-02-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_paper_marking_scheme_file_paper_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='diagram_description',
            field=models.TextField(blank=True, help_text='AI-generated description of diagrams/figures in this question'),
        ),
        migrations.AddField(
            model_name='question',
            name='has_diagram',
            field=models.BooleanField(default=False, help_text='Whether this question includes a diagram/figure/graph'),
        ),
        migrations.AddField(
            model_name='question',
            name='source_page',
            field=models.PositiveIntegerField(blank=True, help_text='Page number in the original PDF where this question appears', null=True),
        ),
    ]
