# Generated by Django 5.0.14 on 2026-02-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_add_source_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='source_position',
            field=models.CharField(blank=True, choices=[('top', 'Top of page'), ('upper', 'Upper section'), ('middle', 'Middle of page'), ('lower', 'Lower section'), ('bottom', 'Bottom of page')], help_text='Approximate vertical position of question on the page', max_length=20),
        ),
    ]
