# Generated by Django 5.0.14 on 2026-02-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_add_source_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='paper_type',
            field=models.CharField(choices=[('paper_1', 'Paper 1'), ('paper_2', 'Paper 2'), ('paper_3', 'Paper 3'), ('paper_4', 'Paper 4'), ('paper_5', 'Paper 5'), ('paper_6', 'Paper 6'), ('practical', 'Practical'), ('theory', 'Theory')], max_length=20),
        ),
    ]
