# Generated by Django 5.0.14 on 2026-02-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_add_paper_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, help_text='For MCQ: the key of correct option (A, B, C, D). For written: brief answer.', max_length=200),
        ),
    ]
