# Generated by Django 5.0.14 on 2026-02-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_increase_correct_answer_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_number',
            field=models.CharField(max_length=50),
        ),
    ]
