# Generated by Django 5.0.14 on 2026-02-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='first_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='pdf_reference_clicks',
            field=models.IntegerField(default=0, help_text='Times the PDF reference was clicked'),
        ),
        migrations.AddField(
            model_name='answer',
            name='time_spent_seconds',
            field=models.IntegerField(default=0, help_text='Total time spent on this question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='view_count',
            field=models.IntegerField(default=0, help_text='Number of times this question was viewed'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='last_activity_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='last_question_index',
            field=models.IntegerField(default=0, help_text='Last question viewed (0-indexed)'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='pdf_last_page_viewed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='pdf_views',
            field=models.IntegerField(default=0, help_text='Number of times original PDF was viewed'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='questions_viewed',
            field=models.JSONField(blank=True, default=list, help_text='List of question IDs that have been viewed'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='total_pause_time_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('paused', 'Paused'), ('submitted', 'Submitted'), ('marked', 'Marked'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20),
        ),
    ]
