# Generated by Django 5.0.14 on 2026-02-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0003_add_source_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='confidence_level',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10),
        ),
        migrations.AddField(
            model_name='answer',
            name='confidence_score',
            field=models.FloatField(blank=True, help_text='0.0-1.0 confidence score', null=True),
        ),
    ]
