# Generated by Django 5.0.14 on 2026-02-14 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0004_answer_confidence_level_answer_confidence_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('marking', 'Marking'), ('calculating', 'Calculating'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('total_questions', models.IntegerField(default=0)),
                ('questions_marked', models.IntegerField(default=0)),
                ('current_question_number', models.CharField(blank=True, max_length=50)),
                ('current_question_text', models.CharField(blank=True, max_length=200)),
                ('messages', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marking_progress', to='attempts.attempt')),
            ],
            options={
                'verbose_name_plural': 'Marking progress',
            },
        ),
    ]
